### ISSUE TITLE
Project Related Experiments 

### ISSUE THREAD

**Issue by rishi11** [abhishek10/CS5610-abhik#5]
Please perform project related experiments. If you have performed any please explain in documentation how that experiment is going to contribute towards your project.

**Comment by abhishek10** [comment]
Which Documentation ? I mentioned it in my blog.

I haven't started writing my project documentation yet. I will start from this week. I will also start check in my code for my project from this week. What I was planning is, once I get to know how to call that external web API and how to parse the response, I will accordingly start writing code for my project. So that part is done (week-9 experiments). From next week onwards I can actually show some progress on project because initially, instead of directly jumping on project code, I wanted to make sure that its feasible and I can implement the core part of the project.

Thanks,
Abhishek

**Comment by rishi11** [comment]
By documentation, I mean to say the documentation of the experiment. You must explain how the experiment contributes to the project.Although, I am not counting this issues in final report.

**Comment by abhishek10** [comment]
Thanks Rishi.
I already added 5 more experiments and now total count is 55. So I think it
should be fine now.

Thanks,
Abhishek
